services:
  lucos_repos:
    build: .
    container_name: lucos_repos_app
    image: lucas42/lucos_repos_app
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT
      - SYSTEM
      - ENVIRONMENT
      - GITHUB_APP_ID
      - GITHUB_APP_PEM
      - SCHEDULE_TRACKER_ENDPOINT
    volumes:
      - data:/data
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:${PORT}/_info"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    restart: always

volumes:
  data:
