services:
  lucos_repos:
    build: .
    container_name: lucos_repos_app
    image: lucas42/lucos_repos_app
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT
      - SYSTEM
      - ENVIRONMENT
      - GITHUB_APP_ID
      - GITHUB_APP_PEM
    volumes:
      - data:/data
    restart: always

volumes:
  data:
