services:
  lucos_repos:
    build: .
    container_name: lucos_repos
    ports: 
      - $PORT:$PORT
    environment:
      - PORT
      - GIT_EMAIL
      - GITHUB_SSH
    image: lucas42/lucos_repos
    restart: always
